### ISSUE TITLE
Feature request: Add evolves to button

### ISSUE THREAD

**Issue by mylogon341** [Frog-Frog/Pokedex#28]
It would be nice to have a button to see what the pokemon evolves into, as well as what it evolves from. 
There appears to be a call needed to `/evolution-chain/id` to get that info, and I cant get my head around the architecture to add that call in to get that information .

**Comment by Frog-Frog** [comment]
@mylogon341 
Hi, mylogon341.
Thank you for creating the Issue.

Indeed, the ability to browse the evolution chain is a good and useful idea.
And as for the process itself, I do believe it can be easily added.

While there are simple evolution chains (like Bulbasaur), there are many complex evolution chains in Pokémon (like Eevee).
I'm currently trying to figure out how to display such complex evolutions in the UI.

If you have any good UI ideas, I'd be happy to hear them.

**Comment by mylogon341** [comment]
Hi. 
I actually went ahead and created my own app in the end. 
Here is the ui implementation that I went with. ￼
With eevee selected, the selection looks like this. 
![image](https://user-images.githubusercontent.com/5493303/106354907-cf9e6400-62ec-11eb-9a1d-ce5de9fbef23.png)

And with any of the other Pokémon selected in the evolution chain, it looks like this. 

![image](https://user-images.githubusercontent.com/5493303/106354943-07a5a700-62ed-11eb-9b34-6fa782109a4b.png)￼

I hope this helps￼. 
Luke

**Comment by Frog-Frog** [comment]
Hi, @mylogon341 
Thanks for the good idea.
I have created a new screen based on the idea.

It needs a little UI adjustment and validation, but I will be able to release the evolution chain screen soon.

|  Single  |  Multiple  |
| ---- | ---- |
|  <img src="https://user-images.githubusercontent.com/20692907/106467947-a8a88380-64e0-11eb-8682-970f1b4801c6.png" width="250">  |  <img src="https://user-images.githubusercontent.com/20692907/106467924-a21a0c00-64e0-11eb-9a67-2147e7aa8b85.gif" width="250">  |

**Comment by mylogon341** [comment]
Nice. Once I’ve tidied up my project, I’ll share some of the features that my 7 year old has requested from my app. 
Some of the other things have been:
- Encounter details for each game
- Evolution details/ requirements for each game
- Level/ TM required for moves per game

Most of my logic is done on a node js server though, so the app is very much a barebones representation of the data that is fetched and sorted by that. A bit of extra setup, but I found it to be a lot easier that way (with JS promises being so easy/ useful)

**Comment by Frog-Frog** [comment]
@mylogon341 
I've implemented the UI design for the evolution chain screen and have just merged it into the develop branch.

|  Single  |  Multiple  |
| ---- | ---- |
|  <img src="https://user-images.githubusercontent.com/20692907/107919957-7d796600-6faf-11eb-9cb2-29767723e30e.png" width="250">  |  <img src="https://user-images.githubusercontent.com/20692907/107919868-5884f300-6faf-11eb-8de1-e3680799f62f.png" width="250">  |

I will close this issue.
Thank you for your great ideas.
