### ISSUE TITLE
synchronizeは非推奨

### ISSUE THREAD

**Issue by crane-hiromu** [Frog-Frog/Pokedex#3]
synchronizeは即時実行してしまうので、クラッシュしてしまう可能性を秘めているので、非推奨になった記憶があります、、、。

https://github.com/Frog-Frog/Pokedex/blob/573f5cf0f9e3d333bda9762489aeb52126edc4bf/DataStore/Storage/UserDefaults/DataStore/UserDefaultsDataStore.swift#L33

**Comment by Frog-Frog** [comment]
@crane-hiromu 
確かに使用すべきでない様ですね。
修正しておきます！
https://developer.apple.com/documentation/foundation/nsuserdefaults/1414005-synchronize
